# Generated by Django 3.2 on 2022-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_messages', '0003_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
