# Generated by Django 3.2 on 2022-02-19 23:12 and @mka142 on 2022-02-20 00:27
from django.db import migrations, models
import uuid

def fill_mymodel_uuid(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    MyModel = apps.get_model('drf_messages', 'message')
    for obj in MyModel.objects.using(db_alias).all():
        obj.uuid = uuid.uuid4()
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('drf_messages', '0003_message_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(fill_mymodel_uuid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='message',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, serialize=False, editable=False, unique=True),
        ),
        migrations.RemoveField('message', 'id'),
        migrations.RenameField(
            model_name='message',
            old_name='uuid',
            new_name='id'
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False, editable=False),
        ),
    ]
